CREATE DATABASE SEGURIDAD
GO 

USE SEGURIDAD
GO 

	/* CRECIÓN DE LAS TABLAS */

CREATE TABLE ROLES(
ROL_ID INT IDENTITY (1,1) PRIMARY KEY, 
ROL_DESCRIPCION VARCHAR (30)
)
GO

CREATE TABLE USUARIOS(
USE_ID INT IDENTITY (1,1) PRIMARY KEY, 
USE_CEDULA VARCHAR (25) UNIQUE NOT NULL,
USE_NOMBRE VARCHAR (80) NOT NULL,
USE_APELLIDO VARCHAR (80) NOT NULL,
USE_TELEFONO VARCHAR (20), 
USE_CORREO VARCHAR (50) NOT NULL,
USE_@NIKNAME VARCHAR (60) NOT NULL,
USE_CONTRASENA VARCHAR (15) NOT NULL
)
GO

CREATE TABLE PERMISO(
PER_ID INT IDENTITY (1,1) PRIMARY KEY,
PER_USER_ID INT REFERENCES USUARIOS (USE_ID),
PER_ROL_ID INT REFERENCES ROLES (ROL_ID)
)
GO

	/* PROCEDIMIENTOS Y DISPARADORES DE LAS TABLAS */

CREATE PROC SP_INSERTAR_ROLES(
@ROL_DESCRIPCION VARCHAR (30)
)

AS
BEGIN 
	INSERT INTO ROLES (ROL_DESCRIPCION)
		       VALUES (@ROL_DESCRIPCION)
END

CREATE PROC SP_INSERTAR_USUARIOS(
@USE_CEDULA VARCHAR (25),
@USE_NOMBRE VARCHAR (80),
@USE_APELLIDO VARCHAR (80),
@USE_TELEFONO VARCHAR (20), 
@USE_CORREO VARCHAR (50),
@USE_@NIKNAME VARCHAR (60),
@USE_CONTRASENA VARCHAR (15)
)

AS
BEGIN 
	INSERT INTO USUARIOS (USE_CEDULA,USE_NOMBRE, USE_APELLIDO, USE_TELEFONO, USE_CORREO, USE_@NIKNAME, USE_CONTRASENA)
		       VALUES (@USE_CEDULA,@USE_NOMBRE, @USE_APELLIDO, @USE_TELEFONO, @USE_CORREO, @USE_@NIKNAME, @USE_CONTRASENA)
END

CREATE TRIGGER TR_CONTADOR_USUARIOS
ON USUARIOS
	FOR INSERT 
AS 
BEGIN 
	SELECT COUNT (USE_ID) AS 'CANTIDAD DE USUARIOS INGRSADOS' FROM USUARIOS
END

create proc sp_validar_insertar_permisos(
@ID_USUARIO VARCHAR (25),
@PER_USER_ID INT,
@PER_ROL_ID INT
)

AS
BEGIN
	SET NOCOUNT ON;

	IF (SELECT PER_USER_ID FROM PERMISO WHERE PER_USER_ID = @ID_USUARIO) = 1
  BEGIN 
	INSERT INTO PERMISO (PER_USER_ID, PER_ROL_ID)
	             VALUES (@PER_USER_ID, @PER_ROL_ID)
  END
	ELSE 
  BEGIN 
	PRINT 'Error... Usuarios Sin Permisos';
  END 
END

CREATE TRIGGER TR_SELECCIONAR_permisos
ON PERMISO 
	FOR INSERT 
AS 
BEGIN 
	SELECT U.USE_NOMBRE AS 'Nombre del Usuario',
		   U.USE_CEDULA AS 'Cedula del Usuario',
		   R.ROL_DESCRIPCION AS 'Permiso Asigando'
	FROM PERMISO P, ROLES R, USUARIOS U
	WHERE P.PER_USER_ID = U.USE_ID AND
	      P.PER_ROL_ID = R.ROL_ID 
END

	/* INGRESAR LOS REGISTROS DE LAS TABLAS */

EXEC SP_INSERTAR_ROLES 'Administrador'
EXEC SP_INSERTAR_ROLES 'Lectura'
EXEC SP_INSERTAR_ROLES 'Escritura'

EXEC SP_INSERTAR_USUARIOS '208230227', 'Maikel', 'Cambronero', '83709711', 'maikelcambro@gmail.com', 'MaikelC07', '1234'
EXEC SP_INSERTAR_USUARIOS '20980465', 'Dennis', 'Rodríguez', '88996543', 'dennisrodri@gmail.com', 'DennisR07', '5678'
EXEC SP_INSERTAR_USUARIOS '208230987', 'Breilyn', 'Pacheco', '12563421', 'breypacheco@gmail.com', 'BreylinP07', '9101112'
EXEC SP_INSERTAR_USUARIOS '209760227', 'Anferny', 'Barquero', '09875467', 'anferbarquero@gmail.com', 'AnfernyB07', '4321'
EXEC SP_INSERTAR_USUARIOS '108230228','Yeilin', 'Quezada', '09453287', 'yeilinquezada@gmail.com', 'YeilinQ07', '987654'

SELECT * FROM ROLES 
SELECT * FROM USUARIOS
SELECT * FROM PERMISO

INSERT INTO PERMISO VALUES (1, 1)

EXEC sp_validar_insertar_permisos '1', 2, 3 -- Con permiso de insertar.
exec sp_validar_insertar_permisos '2', 3, 2 -- sin permiso de insertar.
EXEC sp_validar_insertar_permisos '1', 4, 1 -- CON PERMISO DE INSERTAR POR CORRER.
EXEC sp_validar_insertar_permisos '2', 4, 2 -- SIN PERMISO DE INSERTAR POR CORRER.
